name: CD Pipeline to Vercel (staging and production)

on:
  push:
    branches:
      - staging
  workflow_dispatch: {}
  release:
    types: published

jobs:
  test:
    runs-on: ubuntu-latest
    name: Setup and test project

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy to Vercel

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Deploy to Vercel - Production
        if: github.event_name == 'release' && github.event.action == 'published' && github.event.release.target_commitish == 'main'
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Deploy to Vercel - Staging
        if: github.ref == 'refs/heads/staging'
        run: vercel --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}